# -*- coding: utf-8 -*-
"""Encoder-Only.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oF64dkUNtnaEBunVyKbNWxqt6so-2mqg
"""

import tensorflow as tf
import numpy as np
import pandas as pd
from datasets import load_dataset
import re
import random
from tensorflow import keras

df = pd.read_csv("ranking_dataset.csv")

pairs = []
for i in range(len(df)):
  vals = []
  ranks = []
  for j in range(10):
    vals.append(df.iloc[i, j])
  for k in range(10, 20):
    ranks.append(df.iloc[i, k])
  pairs.append((vals, ranks))

print(pairs[0])

train = pairs[:7000]
eval = pairs[7000:8500]
test = pairs[8500:]

def batches(pairs, batch_size):
    #random.shuffle(pairs)
    for i in range(0, len(pairs) - batch_size + 1, batch_size):

        batch = pairs[i: i + batch_size]

        inputs = []
        targets = []

        for i in batch:
            inputs.append(i[0])
            targets.append(i[1])

        yield tf.constant(inputs, dtype=tf.int32), tf.constant(targets, dtype=tf.int32)

# Commented out IPython magic to ensure Python compatibility.
# %pip install evaluate

class PositionalEncoding(tf.keras.layers.Layer):
    def __init__(self, d_model):
        super().__init__()

        pe = np.zeros((10, d_model))

        positions = np.arange(10).reshape(-1, 1)
        dims = np.arange(0, d_model, 2).reshape(1, -1)

        div_term = np.power(10000, dims/d_model)

        pe[:, 0::2] = np.sin(positions/div_term)
        pe[:, 1::2] = np.cos(positions/div_term)

        self.pe = tf.constant(pe[np.newaxis, :, :], dtype=tf.float32)

    def call(self, x):
        return x + self.pe[:, :tf.shape(x)[1], :]

class MultiHeadAttention(tf.keras.layers.Layer):
    def __init__(self, d_model, num_heads):
        super().__init__()
        self.num_heads = num_heads
        self.d_k = d_model//num_heads

        self.W_Q = tf.keras.layers.Dense(d_model)
        self.W_K = tf.keras.layers.Dense(d_model)
        self.W_V = tf.keras.layers.Dense(d_model)

        self.W = tf.keras.layers.Dense(d_model)

    def split(self, x, batchsize):
        x = tf.reshape(x, (batchsize, -1, self.num_heads, self.d_k))

        return tf.transpose(x, perm=[0, 2, 1, 3])
        #(batch, num_heads, 10, d_k)

    def computation(self, Q, K, V):
        # Q @ K^T
        scores  = tf.matmul(Q, K, transpose_b=True)
        # divide by sqrt(d_k)
        scores  = scores/tf.math.sqrt(tf.cast(self.d_k, tf.float32))
        weights = tf.nn.softmax(scores, axis=-1)
        output  = tf.matmul(weights, V)
        return output, weights

    def call(self, x):
        batch_size = tf.shape(x)[0]
        Q = self.split(self.W_Q(x), batch_size)
        K = self.split(self.W_K(x), batch_size)
        V = self.split(self.W_V(x), batch_size)

        attn_out, weights = self.computation(Q, K, V)
        #(batch, heads, seq, d_k)

        attn_out = tf.transpose(attn_out, perm=[0, 2, 1, 3])
        #(batch, seq, heads, d_k)

        attn_out = tf.reshape(attn_out, (batch_size, -1, self.num_heads * self.d_k))
        #(batch, seq, d_model)

        return self.W(attn_out)


class Encoder(tf.keras.layers.Layer):
    def __init__(self, d_model, num_heads, f_dim):
        super().__init__()
        self.attention = MultiHeadAttention(d_model, num_heads)
        self.ff1 = tf.keras.layers.Dense(f_dim, activation='relu')
        self.ff2 = tf.keras.layers.Dense(d_model)
        self.norm1 = tf.keras.layers.LayerNormalization()
        self.norm2 = tf.keras.layers.LayerNormalization()

    def call(self, x):
        attn_out = self.attention(x)
        x = self.norm1(x + attn_out)

        ff_out = self.ff2(self.ff1(x))
        x = self.norm2(x + ff_out) #residual connection

        return x

d_model = 128
num_heads = 8
f_dim = 256

batchsize = 100
EPOCHS = 25
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(axis = -1)
optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3)

print(train[:5])
print(batches(train[:5], 5))

for Xtrain, ytrain in batches(train[:2], 2):
    print("X =", Xtrain)
    print("y =", ytrain)
    break

inputs = tf.keras.Input(shape=(10,1))
emb = tf.keras.layers.Dense(d_model)(inputs)
emb = PositionalEncoding(d_model)(emb)
out = Encoder(d_model, num_heads, f_dim)(emb)
#out = tf.keras.layers.Dropout(0.4)(out)
out = tf.keras.layers.Dense(10, activation = 'softmax')(out)
Transformer = tf.keras.Model(inputs, out)

#emb.shape

import evaluate

losstrack = []
acctrack = []

for epoch in range(1, EPOCHS + 1):

    accuracy_metric = evaluate.load("accuracy")

    #training

    train_loss, steps = 0, 0
    for Xtrain, ytrain in batches(train, batchsize):
        with tf.GradientTape() as tape:
            predictions = Transformer(Xtrain, training=True)
            loss = loss_fn(ytrain, predictions)
        grads = tape.gradient(loss, Transformer.trainable_variables)
        optimizer.apply_gradients(zip(grads, Transformer.trainable_variables))
        train_loss += loss.numpy()
        steps += 1

    losstrack.append(train_loss/steps)

    #validation

    for Xval, yval in batches(eval, batchsize):
        predictions = Transformer(Xval, training=False)
        preds = tf.argmax(predictions, axis=-1).numpy().flatten()
        targets = yval.numpy().flatten()
        accuracy_metric.add_batch(predictions=preds, references=targets)

    val_acc = accuracy_metric.compute()["accuracy"] * 100
    acctrack.append(val_acc)

    print(f"Epoch {epoch:02d}/{EPOCHS}  Loss: {train_loss/steps:.4f}  Val Acc: {val_acc:.2f}%")

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(losstrack, label='Train Loss')
plt.title('Loss over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(acctrack, label='Validation Accuracy')
plt.title('Accuracy over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.tight_layout()
plt.show()

#testing

for Xtest, ytest in batches(test, batchsize):
        predictions = Transformer(Xtest, training=False)
        preds = tf.argmax(predictions, axis=-1).numpy().flatten()
        targets = ytest.numpy().flatten()
        accuracy_metric.add_batch(predictions=preds, references=targets)

test_acc = accuracy_metric.compute()["accuracy"] * 100
print(f"\nTest Acc: {test_acc:.2f}%")

for X,y  in batches(eval[:1],1):
  pred = Transformer(X, training=False)
  pred = tf.argmax(pred, axis=-1)

print(pred.numpy()[0])
print(y.numpy()[0])

print(np.mean(pred.numpy()[0] == y.numpy()[0]))

accs = []

for X, y in batches(train[:100], 1):
    pred = Transformer(X, training=False)
    pred = tf.argmax(pred, axis=-1)

    accs.append(
        np.mean(pred.numpy()[0] == y.numpy()[0])
    )

print(np.mean(accs))
print(np.min(accs))
print(np.max(accs))

pred_probs = Transformer(X, training=False)

for i in range(10):
    print(pred_probs[0, i].numpy())