# -*- coding: utf-8 -*-
"""BaselineModels-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tqFHhNFWiRjzHHXrH6yYtVLoKFYTAkI2
"""

import tensorflow as tf
import numpy as np
import pandas as pd
from datasets import load_dataset
import re
import random
from tensorflow import keras
import matplotlib.pyplot as plt

df = pd.read_csv("ranking_dataset.csv")
print(df.head())

len(df)

pairs = []
for i in range(len(df)):
  vals = []
  ranks = []
  for j in range(10):
    vals.append(df.iloc[i, j])
  for k in range(10, 20):
    ranks.append(df.iloc[i, k])
  pairs.append((vals, ranks))

print(pairs[0])

train = pairs[:7000]
eval = pairs[7000:8500]
test = pairs[8500:]

def batches(pairs, batch_size):
    #random.shuffle(pairs)
    for i in range(0, len(pairs) - batch_size + 1, batch_size):

        batch = pairs[i: i + batch_size]

        inputs = []
        targets = []

        for i in batch:
            inputs.append(i[0])
            targets.append(i[1])

        yield tf.constant(inputs, dtype=tf.int32), tf.constant(targets, dtype=tf.int32)



#[([],[]),([],[]),([],[])]
#([],[])

#X, y = batches(pairs, 5)
#X = tf.expand_dims(X, -1)

print(type(batches(pairs, 5)))
#print(len(batches(pairs, 5)))

#print(X[0])

# Commented out IPython magic to ensure Python compatibility.
# %pip install evaluate

"""MLP"""

batchsize = 100
d_model = 256
EPOCHS = 30
loss_fn = keras.losses.SparseCategoricalCrossentropy(from_logits=False)
optimizer = keras.optimizers.Adam(learning_rate=1e-3)

mlp = keras.Sequential([keras.layers.Input(shape=(10,1)),
keras.layers.Dense(d_model, activation= 'relu'),
keras.layers.Dense(d_model, activation= 'relu'),
keras.layers.Dropout(0.3),
keras.layers.Dense(10, activation='softmax')])

import evaluate

losstrack = []
acctrack = []

for epoch in range(1, EPOCHS + 1):

    accuracy_metric = evaluate.load("accuracy")

    #training

    train_loss, steps = 0, 0
    for Xtrain, ytrain in batches(train, batchsize):
        with tf.GradientTape() as tape:
            predictions = mlp(Xtrain, training=True)
            loss = loss_fn(ytrain, predictions)
        grads = tape.gradient(loss, mlp.trainable_variables)
        optimizer.apply_gradients(zip(grads, mlp.trainable_variables))
        train_loss += loss.numpy()
        steps += 1

    losstrack.append(train_loss/steps)

    #validation

    for Xval, yval in batches(eval, batchsize):
        predictions = mlp(Xval, training=False)
        preds = tf.argmax(predictions, axis=-1).numpy().flatten()
        targets = yval.numpy().flatten()
        accuracy_metric.add_batch(predictions=preds, references=targets)

    val_acc = accuracy_metric.compute()["accuracy"] * 100
    acctrack.append(val_acc)

    print(f"Epoch {epoch:02d}/{EPOCHS}  Loss: {train_loss/steps:.4f}  Val Acc: {val_acc:.2f}%")

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(losstrack, label='Train Loss')
plt.title('Loss over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(acctrack, label='Validation Accuracy')
plt.title('Accuracy over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.tight_layout()
plt.show()

#testing

for Xtest, ytest in batches(test, batchsize):
        predictions = mlp(Xtest, training=False)
        preds = tf.argmax(predictions, axis=-1).numpy().flatten()
        targets = ytest.numpy().flatten()
        accuracy_metric.add_batch(predictions=preds, references=targets)

test_acc = accuracy_metric.compute()["accuracy"] * 100
print(f"\nTest Acc: {test_acc:.2f}%")

"""RNN"""

batchsize = 100
d_model = 128
EPOCHS = 15
loss_fn = keras.losses.SparseCategoricalCrossentropy(from_logits=True)
optimizer = keras.optimizers.Adam(learning_rate=1e-3)

rnn = keras.Sequential([keras.layers.Input(shape=(10,1)),
keras.layers.Dense(d_model),
keras.layers.SimpleRNN(d_model, return_sequences=True),
keras.layers.Dropout(0.4),
keras.layers.Dense(10)])

import evaluate

losstrack = []
acctrack = []

for epoch in range(1, EPOCHS + 1):

    accuracy_metric = evaluate.load("accuracy")

    #training

    train_loss, steps = 0, 0
    for Xtrain, ytrain in batches(train, batchsize):
        with tf.GradientTape() as tape:
            predictions = rnn(Xtrain, training=True)
            loss = loss_fn(ytrain, predictions)
        grads = tape.gradient(loss, rnn.trainable_variables)
        optimizer.apply_gradients(zip(grads, rnn.trainable_variables))
        train_loss += loss.numpy()
        steps += 1

    losstrack.append(train_loss/steps)

    #validation

    for Xval, yval in batches(eval, batchsize):
        predictions = rnn(Xval, training=False)
        preds = tf.argmax(predictions, axis=-1).numpy().flatten()
        targets = yval.numpy().flatten()
        accuracy_metric.add_batch(predictions=preds, references=targets)

    val_acc = accuracy_metric.compute()["accuracy"] * 100
    acctrack.append(val_acc)

    print(f"Epoch {epoch:02d}/{EPOCHS}  Loss: {train_loss/steps:.4f}  Val Acc: {val_acc:.2f}%")

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(losstrack, label='Train Loss')
plt.title('Loss over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(acctrack, label='Validation Accuracy')
plt.title('Accuracy over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.tight_layout()
plt.show()

#testing

for Xtest, ytest in batches(test, batchsize):
        predictions = rnn(Xtest, training=False)
        preds = tf.argmax(predictions, axis=-1).numpy().flatten()
        targets = ytest.numpy().flatten()
        accuracy_metric.add_batch(predictions=preds, references=targets)

test_acc = accuracy_metric.compute()["accuracy"] * 100
print(f"\nTest Acc: {test_acc:.2f}%")

"""LSTM"""

batchsize = 100
d_model = 128
EPOCHS = 25
loss_fn = keras.losses.SparseCategoricalCrossentropy(from_logits=False)
optimizer = keras.optimizers.Adam(learning_rate=0.0001)

lstm = keras.Sequential([keras.layers.Input(shape=(10,1)),
keras.layers.Dense(d_model),
keras.layers.LSTM(d_model, return_sequences=True),
keras.layers.Dropout(0.3),
keras.layers.LSTM(d_model, return_sequences=True),
keras.layers.Dropout(0.4),
keras.layers.Dense(10, activation = 'softmax')])

import evaluate

losstrack = []
acctrack = []

for epoch in range(1, EPOCHS + 1):

    accuracy_metric = evaluate.load("accuracy")

    #training

    train_loss, steps = 0, 0
    for Xtrain, ytrain in batches(train, batchsize):
        with tf.GradientTape() as tape:
            predictions = lstm(Xtrain, training=True)
            loss = loss_fn(ytrain, predictions)
        grads = tape.gradient(loss, lstm.trainable_variables)
        optimizer.apply_gradients(zip(grads, lstm.trainable_variables))
        train_loss += loss.numpy()
        steps += 1

    losstrack.append(train_loss/steps)

    #validation

    for Xval, yval in batches(eval, batchsize):
        predictions = lstm(Xval, training=False)
        preds = tf.argmax(predictions, axis=-1).numpy().flatten()
        targets = yval.numpy().flatten()
        accuracy_metric.add_batch(predictions=preds, references=targets)

    val_acc = accuracy_metric.compute()["accuracy"] * 100
    acctrack.append(val_acc)

    print(f"Epoch {epoch:02d}/{EPOCHS}  Loss: {train_loss/steps:.4f}  Val Acc: {val_acc:.2f}%")

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(losstrack, label='Train Loss')
plt.title('Loss over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(acctrack, label='Validation Accuracy')
plt.title('Accuracy over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.tight_layout()
plt.show()

#testing

for Xtest, ytest in batches(test, batchsize):
        predictions = lstm(Xtest, training=False)
        preds = tf.argmax(predictions, axis=-1).numpy().flatten()
        targets = ytest.numpy().flatten()
        accuracy_metric.add_batch(predictions=preds, references=targets)

test_acc = accuracy_metric.compute()["accuracy"] * 100
print(f"\nTest Acc: {test_acc:.2f}%")

