# -*- coding: utf-8 -*-
"""BaselineModels-3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LYu3LjRMj2QxZISuFs70Nayu2UaxTqpl
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from datasets import load_dataset

import pandas as pd
import numpy as np

ds = load_dataset("merve/poetry")

df = pd.DataFrame(ds["train"])
df.head()

print(df["content"][2])

df["content"] = "<s> " + df["content"] + " </s>"

print(df["content"][2])

import re

#Preprocessing

text = " ".join(df["content"].astype(str))
text = text.replace("\r\n", " ")
text = text.lower()
text = re.sub(r'([,;.!?])', r' \1 ', text) #stylistic choice
text = re.sub(r'\s+', ' ', text).strip()
tokens = text.split(" ")
unique = sorted(set(tokens))
print(tokens)

"""BIGRAM:"""

#for frequency/counting implementation

grouping = []
for i in range(len(tokens)-1):
    grouping.append((tokens[i], tokens[i+1]))

print(grouping[:10])
len(grouping)
grouping = [x for x in grouping if x != ('</s>', '<s>')]

"""gMLP"""

class Tokenizer:
    def __init__(self):

        self.word2idx = {"<PAD>": 0, "<UNK>": 1, "<s>": 2, "</s>": 3}
        self.idx2word = {0: "<PAD>", 1: "<UNK>", 2: "<s>", 3: "</s>"}
        self.vocab_size = 4

    def fit(self, splitwords):

        for word in splitwords:
            if word not in self.word2idx:
                self.word2idx[word] = self.vocab_size
                self.idx2word[self.vocab_size] = word
                self.vocab_size += 1

    def encode(self, splitwords):
        return [self.word2idx.get(word.lower(), self.word2idx["<UNK>"]) for word in splitwords]

    def decode(self, indice):
        return " ".join([self.idx2word.get(idx, "<UNK>") for idx in indice])

class SGU(nn.Module):

    def __init__(self, d_model, poemlen):
        super().__init__()

        self.spatial_proj = nn.Conv1d(poemlen, poemlen, kernel_size=1)
        self.norm = nn.LayerNorm(d_model//2)
        self.spatial_proj.weight.data.zero_()
        self.spatial_proj.bias.data.fill_(1.0)

    def forward(self, x):
        u, v = x.chunk(2, dim=-1)

        v = self.norm(v)
        v = self.spatial_proj(v)

        return u*v

class gMLPBlock(nn.Module):

    def __init__(self, d_model, poemlen, expansion_factor=4):
        super().__init__()

        self.norm = nn.LayerNorm(d_model)

        hidden_dim = d_model*expansion_factor

        self.channel_proj1 = nn.Linear(d_model, hidden_dim)

        self.act = nn.GELU()
        self.sgu = SGU(hidden_dim, poemlen)

        self.channel_proj2 = nn.Linear(hidden_dim//2, d_model)

    def forward(self, x):
        residual = x

        x = self.norm(x)
        x = self.channel_proj1(x)
        x = self.act(x)
        x = self.sgu(x)
        x = self.channel_proj2(x)

        return x+residual

class gMLP(nn.Module):

    def __init__(self, vocab_size, d_model, poemlen, num_layers):
        super().__init__()

        self.token_emb = nn.Embedding(vocab_size, d_model)
        self.pos_emb = nn.Parameter(torch.zeros(1, poemlen, d_model))

        nn.init.normal_(self.pos_emb, std=0.02)

        self.layers = nn.ModuleList([gMLPBlock(d_model, poemlen) for i in range(num_layers)])
        self.finalnorm = nn.LayerNorm(d_model)

        self.tologits = nn.Linear(d_model, vocab_size)

    def forward(self, x):
        b, t = x.size()

        x = self.token_emb(x) + self.pos_emb[:,:t,:]

        for layer in self.layers:
            x = layer(x)

        return self.tologits(self.finalnorm(x))

tokenizer = Tokenizer()
tokenizer.fit(tokens)

encoded = tokenizer.encode(tokens)

print(tokenizer.vocab_size)
print(tokens)
print(encoded)

def batches(data, batch_size, mode):

    sentences = []
    current_sentence = []
    for token in data:
        current_sentence.append(token)
        if token == 3:
            sentences.append(current_sentence)
            current_sentence = []

    maxlen = max_len
    sentences = [s for s in sentences if len(s) <= maxlen + 1]

    rng = random.Random(42)
    rng.shuffle(sentences)

    split_idx = int(len(sentences)*0.8)

    if mode == "train": #introducting train mode in order to flip between training and eval
        sentences = sentences[:split_idx]
    else:
        sentences = sentences[split_idx:]

    allinputs, alltargets = [], []


    for s in sentences:

        inp = s[:-1]
        tar = s[1:]

        inp += [0]*(maxlen-len(inp))
        tar += [0]*(maxlen-len(tar))

        allinputs.append(inp)

        alltargets.append(tar)


    inputs = torch.tensor(allinputs, dtype=torch.long)

    targets = torch.tensor(alltargets, dtype=torch.long)


    for i in range(0, len(inputs) - batch_size + 1, batch_size):
        yield inputs[i: i + batch_size], targets[i: i + batch_size]

batchsize = 16
d_model = 128
num_layers = 2
EPOCHS = 50

lengths, current_len = [], 0

for token in encoded:
    current_len += 1
    if token == 3:
        lengths.append(current_len)
        current_len = 0

print(lengths)

max_len = 200 #capping at 200 tokens after analysing list


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = gMLP(tokenizer.vocab_size, d_model, max_len, num_layers).to(device)
optimizer = torch.optim.AdamW(model.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss(ignore_index=0)

# Commented out IPython magic to ensure Python compatibility.
# %pip install evaluate

import evaluate

losstrack = []
acctrack = []

for epoch in range(1, EPOCHS + 1):

    accuracy_metric = evaluate.load("accuracy")

    model.train()
    #starts with training part of epoch
    loss_sum, steps = 0, 0
    for x, y in batches(encoded, batchsize, "train"):
        x, y = x.to(device), y.to(device)
        optimizer.zero_grad()
        loss = criterion(model(x).view(-1, tokenizer.vocab_size), y.view(-1))
        loss.backward()
        optimizer.step()
        loss_sum, steps = loss_sum + loss.item(), steps + 1

    losstrack.append(loss_sum)

    model.eval()
    #flips to eval part of epoch
    with torch.no_grad():

        for x, y in batches(encoded, batchsize, "eval"):

            x, y = x.to(device), y.to(device)

            preds = torch.argmax(model(x), -1).view(-1)
            targets = y.view(-1)

            mask = targets!=0

            accuracy_metric.add_batch(predictions=preds[mask].tolist(), references=targets[mask].tolist())

    final_score = accuracy_metric.compute()["accuracy"] * 100
    acctrack.append(final_score)

    print(f"Epoch {epoch:02d}/{EPOCHS}  Loss: {loss_sum/steps:.4f}  Validation Acc: {final_score:.2f}%")

import matplotlib.pyplot as plt
plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(losstrack, label='Train Loss')
plt.title('Loss over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(acctrack, label='Validation Accuracy')
plt.title('Accuracy over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.tight_layout()
plt.show()

"""LSTM"""

class LSTM(nn.Module):
    def __init__(self, vocab_size, d_model, num_layers):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, d_model, padding_idx=0)
        self.lstm = nn.LSTM(
            d_model, d_model,
            num_layers=num_layers,
            batch_first=True,
            bidirectional=False,
            dropout=0.3 if num_layers > 1 else 0
        )
        self.dropout = nn.Dropout(0.3)

        self.fc = nn.Linear(d_model, vocab_size)
        self.residual_proj = nn.Linear(d_model, d_model) #adding a residual layer

    def forward(self, x):
        emb = self.dropout(self.embedding(x))

        out, _ = self.lstm(emb)
        out = out + self.residual_proj(emb)

        return self.fc(self.dropout(out))

batchsize = 16
d_model = 256
num_layers = 3
EPOCHS = 75

lengths, current_len = [], 0

for token in encoded:
    current_len += 1
    if token == 3:
        lengths.append(current_len)
        current_len = 0

print(lengths)

max_len = 300


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = LSTM(tokenizer.vocab_size, d_model, num_layers).to(device)
optimizer = torch.optim.AdamW(model.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss(ignore_index=0)

import random


losstrack = []
acctrack = []


for epoch in range(1, EPOCHS + 1):
    accuracy_metric = evaluate.load("accuracy")

    model.train()
    #starts with training part of epoch

    loss_sum, steps = 0, 0

    for x, y in batches(encoded, batchsize, "train"):
        x, y = x.to(device), y.to(device)
        optimizer.zero_grad()
        loss = criterion(model(x).view(-1, tokenizer.vocab_size), y.view(-1))
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()
        loss_sum, steps = loss_sum + loss.item(), steps + 1
    losstrack.append(loss_sum)

    model.eval()
    #flips to eval part of epoch
    with torch.no_grad():

        for x, y in batches(encoded, batchsize, "eval"):

            x, y = x.to(device), y.to(device)

            preds = torch.argmax(model(x), -1).view(-1)
            targets = y.view(-1)

            mask = targets!=0

            accuracy_metric.add_batch(predictions=preds[mask].tolist(), references=targets[mask].tolist())

    final_score = accuracy_metric.compute()["accuracy"] * 100
    acctrack.append(final_score)

    print(f"Epoch {epoch:02d}/{EPOCHS}  Loss: {loss_sum/steps:.4f}  Validation Acc: {final_score:.2f}%")

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(losstrack, label='Train Loss')
plt.title('Loss over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(acctrack, label='Validation Accuracy')
plt.title('Accuracy over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.tight_layout()
plt.show()

"""Vanilla RNN"""

batchsize = 16
d_model = 128
num_layers = 3
EPOCHS = 100

max_len = 270

class RNN(nn.Module):
    def __init__(self, vocab_size, d_model, num_layers):
        super().__init__()

        self.embedding = nn.Embedding(vocab_size, d_model, padding_idx=0)
        self.rnn = nn.RNN(d_model, d_model, num_layers=num_layers, batch_first=True)
        self.fc = nn.Linear(d_model, vocab_size)

    def forward(self, x):

        emb = self.embedding(x)
        out, _ = self.rnn(emb)
        return self.fc(out)


model = RNN(tokenizer.vocab_size, d_model, num_layers).to(device)
optimizer = torch.optim.AdamW(model.parameters(), lr=0.001)

import random

losstrack = []
acctrack = []

for epoch in range(1, EPOCHS + 1):

    accuracy_metric = evaluate.load("accuracy")
    model.train()
    #starts with training part of epoch

    loss_sum, steps = 0, 0

    for x, y in batches(encoded, batchsize, "train"):
        x, y = x.to(device), y.to(device)
        optimizer.zero_grad()
        loss = criterion(model(x).view(-1, tokenizer.vocab_size), y.view(-1))
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()
        loss_sum, steps = loss_sum + loss.item(), steps + 1

    losstrack.append(loss_sum)
    model.eval()
    #flips to eval part of epoch
    with torch.no_grad():

        for x, y in batches(encoded, batchsize, "eval"):

            x, y = x.to(device), y.to(device)

            preds = torch.argmax(model(x), -1).view(-1)
            targets = y.view(-1)

            mask = targets!=0

            accuracy_metric.add_batch(predictions=preds[mask].tolist(), references=targets[mask].tolist())

    final_score = accuracy_metric.compute()["accuracy"] * 100
    acctrack.append(final_score)

    print(f"Epoch {epoch:02d}/{EPOCHS}  Loss: {loss_sum/steps:.4f}  Validation Acc: {final_score:.2f}%")

import matplotlib.pyplot as plt
plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(losstrack, label='Train Loss')
plt.title('Loss over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(acctrack, label='Validation Accuracy')
plt.title('Accuracy over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.tight_layout()
plt.show()

"""# DEMO

**BIGRAM**
"""

import random

counts = {}

for w1, w2 in grouping:
    if w1 not in counts:
        counts[w1] = {}
    if w2 not in counts[w1]:
        counts[w1][w2] = 0

    counts[w1][w2] += 1

current_word = "<s>"
sentence = []

while True:
    if current_word not in counts:
        break
    next = list(counts[current_word].keys())
    ws = list(counts[current_word].values())

    chosen = random.choices(next, weights=ws)[0]

    if chosen == "</s>":
        break

    sentence.append(chosen)
    current_word = chosen

print("Poem:", " ".join(sentence))

max_len = 200

"""**gMLP**"""

model = gMLP(tokenizer.vocab_size, d_model, max_len, num_layers).to(device)
optimizer = torch.optim.AdamW(model.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss(ignore_index=0)

model.eval()

generated = tokenizer.encode(["the"])


with torch.no_grad():

    for _ in range(max_len + 1):
        inputs = generated[-max_len:]

        paddingneeded = max(0, max_len - len(inputs))
        inputs = [0] * paddingneeded + inputs

        x = torch.tensor([inputs], dtype=torch.long, device=device)

        next_tok = torch.argmax(model(x)[0, -1]).item() #greedy decoding used

        generated.append(next_tok)

        if next_tok == 3:
            break

print(f"Generated Poem: '{tokenizer.decode(generated)}'")

with torch.no_grad():
    inputs = [0] * (max_len - 1) + [2]  # padded <s>
    x      = torch.tensor([inputs], dtype=torch.long, device=device)
    logits = model(x)[0, -1]
    probs  = torch.softmax(logits, dim=-1)

    top5_probs, top5_ids = torch.topk(probs, 5)

    for prob, idx in zip(top5_probs, top5_ids):
        print(f"{tokenizer.idx2word[idx.item()]:15} {prob.item()*100:.2f}%")

"""**RNN**"""

model = RNN(tokenizer.vocab_size, d_model, num_layers).to(device)

model.eval()

generated = tokenizer.encode(["i"])


with torch.no_grad():

    for i in range(max_len + 1):
        inputs = generated[-max_len:]

        paddingneeded = max(0, max_len - len(inputs))
        inputs = [0] * paddingneeded + inputs

        x = torch.tensor([inputs], dtype=torch.long, device=device)

        next_tok = torch.argmax(model(x)[0, -1]).item() #greedy decoding used

        generated.append(next_tok)

        if next_tok == 3:
            break

print(f"Generated Poem: '{tokenizer.decode(generated)}'")

"""**LSTM**"""

model = LSTM(tokenizer.vocab_size, d_model, num_layers).to(device)


model.eval()

generated = tokenizer.encode(["he"])


with torch.no_grad():

    for i in range(max_len + 1):
        inputs = generated[-max_len:]

        paddingneeded = max(0, max_len - len(inputs))
        inputs = [0] * paddingneeded + inputs

        x = torch.tensor([inputs], dtype=torch.long, device=device)

        next_tok = torch.argmax(model(x)[0, -1]).item() #greedy decoding used

        generated.append(next_tok)

        if next_tok == 3:
            break

print(f"Generated Poem: '{tokenizer.decode(generated)}'")

with torch.no_grad():
    inputs = [0] * (max_len - 1) + [2]  # padded <s>
    x      = torch.tensor([inputs], dtype=torch.long, device=device)
    logits = model(x)[0, -1]
    probs  = torch.softmax(logits, dim=-1)

    top5_probs, top5_ids = torch.topk(probs, 5)

    for prob, idx in zip(top5_probs, top5_ids):
        print(f"{tokenizer.idx2word[idx.item()]:15} {prob.item()*100:.2f}%")

import math

model.eval()
total_loss, total_tokens = 0, 0

criterion_per_token = nn.CrossEntropyLoss(ignore_index=0, reduction='sum')

with torch.no_grad():
    for x, y in batches(encoded, batchsize, "eval"):
        x, y    = x.to(device), y.to(device)
        logits  = model(x).view(-1, tokenizer.vocab_size)
        targets = y.view(-1)
        loss    = criterion_per_token(logits, targets)
        total_loss   += loss.item()
        total_tokens += (targets != 0).sum().item()

perplexity = math.exp(total_loss / total_tokens)
print(f"Perplexity: {perplexity:.2f}")

# sanity check — perplexity on TRAINING data should be much lower
total_loss, total_tokens = 0, 0
with torch.no_grad():
    for x, y in batches(encoded, batchsize, "train"):
        x, y   = x.to(device), y.to(device)
        logits = model(x).view(-1, tokenizer.vocab_size)
        loss   = criterion_per_token(logits, y.view(-1))
        total_loss   += loss.item()
        total_tokens += (y.view(-1) != 0).sum().item()

print(f"Train perplexity: {math.exp(total_loss/total_tokens):.2f}")
