# -*- coding: utf-8 -*-
"""BaselineModels-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hSA_NkX1U4JdZ-kNTKSGABnG_OSf6Bu5
"""

import tensorflow as tf
import numpy as np
import pandas as pd
from datasets import load_dataset
import re
import random
from tensorflow import keras

ds = load_dataset("google/code_x_glue_cc_code_refinement", "small")

dftrain = pd.DataFrame(ds["train"])
dftest = pd.DataFrame(ds["test"])
dfval = pd.DataFrame(ds["validation"])

dftrain.head()

print(dftrain["buggy"][0])

dftrain["buggy"], dftrain["fixed"] = "<s> " + dftrain["buggy"] + " </s>", "<s> " + dftrain["fixed"] + " </s>"

pairs = []
for i in range(len(dftrain)):
  pairs.append((dftrain["buggy"][i], dftrain["fixed"][i]))
print(pairs[0])

for i in range(len(pairs)):
  pairs[i] = (pairs[i][0].split(), pairs[i][1].split())
print(pairs[0])

allbuggy = " ".join(dftrain["buggy"].astype(str))
allfixed = " ".join(dftrain["fixed"].astype(str))
tokens = allbuggy + " " + allfixed
tokens = tokens.split()
unique = sorted(set(tokens))

print(tokens)

class Tokenizer:
    def __init__(self):

        self.word2idx = {"<PAD>": 0, "<UNK>": 1, "<s>": 2, "</s>": 3}
        self.idx2word = {0: "<PAD>", 1: "<UNK>", 2: "<s>", 3: "</s>"}
        self.vocab_size = 4

    def fit(self, splitwords):

        for word in splitwords:
            if word not in self.word2idx:
                self.word2idx[word] = self.vocab_size
                self.idx2word[self.vocab_size] = word
                self.vocab_size += 1

    def encode(self, splitwords):
        return [self.word2idx.get(word, self.word2idx["<UNK>"]) for word in splitwords]

    def decode(self, indice):
        return " ".join([self.idx2word.get(idx, "<UNK>") for idx in indice])

tokenizer = Tokenizer()
tokenizer.fit(unique)

encoded = []
for i in range(len(pairs)):
  encoded.append((tokenizer.encode(pairs[i][0]), tokenizer.encode(pairs[i][1])))

def prepare(df, tokenizer):
  df.copy()
  df["buggy"], df["fixed"] = "<s> " + df["buggy"] + " </s>", "<s> " + df["fixed"] + " </s>"
  pairs = []
  for i in range(len(df)):
    pairs.append((df["buggy"][i], df["fixed"][i]))
  for i in range(len(pairs)):
    pairs[i] = (pairs[i][0].split(), pairs[i][1].split())

  allbuggy = " ".join(dftrain["buggy"].astype(str))
  allfixed = " ".join(dftrain["fixed"].astype(str))
  tokens = sorted(set((allbuggy + " " + allfixed).split()))

  encoded = []
  for i in range(len(pairs)):
    encoded.append((tokenizer.encode(pairs[i][0]), tokenizer.encode(pairs[i][1])))

  return pairs, encoded

valpairs, valenc = prepare(dfval, tokenizer)
testpairs, testenc = prepare(dftest, tokenizer)

def batches(pairs, batch_size):
    #random.shuffle(pairs)
    for i in range(0, len(pairs) - batch_size + 1, batch_size):

        batch = pairs[i: i + batch_size]

        max_e = max(len(x[0]) for x in batch)
        max_d = max(len(x[1]) for x in batch)

        enc_inputs, dec_inputs, dec_targets = [], [], []

        for i in batch:
            enc_inputs.append(i[0] + [0] * (max_e - len(i[0])))
            dec_inputs.append(i[1][:-1] + [0] * (max_d - len(i[1][:-1])))
            dec_targets.append(i[1][1:] + [0] * (max_d - len(i[1][1:])))

        yield (
            tf.constant(enc_inputs, dtype=tf.int32),
            tf.constant(dec_inputs, dtype=tf.int32),
            tf.constant(dec_targets, dtype=tf.int32)
        )


#[([],[]),([],[]),([],[])]
#([],[])

"""RNN"""

batchsize = 64
d_model = 256
EPOCHS = 25
loss_fn = keras.losses.SparseCategoricalCrossentropy(from_logits=True, ignore_class = 0)
optimizer = keras.optimizers.Adam(learning_rate=0.001)

#encoder

enc_inputs = keras.Input(shape=(None,))
enc_emb  = keras.layers.Embedding(tokenizer.vocab_size, d_model, mask_zero=True)(enc_inputs)
enc_out, enc_state = keras.layers.SimpleRNN(d_model, return_state=True)(enc_emb)

rnnencoder = keras.Model(enc_inputs, enc_state)

#decoder

dec_inputs = keras.Input(shape=(None,))
dec_emb = keras.layers.Embedding(tokenizer.vocab_size, d_model, mask_zero=True)(dec_inputs)
state_in = keras.Input(shape=(d_model,))
dec_out, _ = keras.layers.SimpleRNN(d_model, return_sequences=True, return_state=True)(dec_emb, initial_state=state_in)
dec_out = keras.layers.Dense(tokenizer.vocab_size)(dec_out)

rnndecoder = keras.Model([dec_inputs, state_in], dec_out)

# Commented out IPython magic to ensure Python compatibility.
# %pip install evaluate

import evaluate

losstrack = []
acctrack = []

for epoch in range(1, EPOCHS + 1):

    accuracy_metric = evaluate.load("accuracy")

    #training

    train_loss, steps = 0, 0
    for enc_in, dec_in, dec_tar in batches(encoded[:2500], batchsize):
        with tf.GradientTape() as tape:
            enc  = rnnencoder(enc_in, training=True)
            predictions = rnndecoder([dec_in, enc], training=True)
            loss = loss_fn(dec_tar, predictions)
        grads = tape.gradient(loss, rnnencoder.trainable_variables + rnndecoder.trainable_variables)
        optimizer.apply_gradients(zip(grads, rnnencoder.trainable_variables + rnndecoder.trainable_variables))
        train_loss += loss.numpy()
        steps += 1

    losstrack.append(train_loss/steps)

    #validation

    for enc_in, dec_in, dec_tar in batches(valenc[:1000], batchsize):
        enc = rnnencoder(enc_in, training=False)
        predictions = rnndecoder([dec_in, enc], training=False)
        preds = tf.argmax(predictions, axis=-1).numpy().flatten()
        targets = dec_tar.numpy().flatten()
        mask  = targets != 0
        accuracy_metric.add_batch(predictions=preds[mask], references=targets[mask])

    val_acc = accuracy_metric.compute()["accuracy"] * 100
    acctrack.append(val_acc)

    print(f"Epoch {epoch:02d}/{EPOCHS}  Loss: {train_loss/steps:.4f}  Val Acc: {val_acc:.2f}%")

import matplotlib.pyplot as plt
plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(losstrack, label='Train Loss')
plt.title('Loss over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(acctrack, label='Validation Accuracy')
plt.title('Accuracy over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.tight_layout()
plt.show()

#testing

for enc_in, dec_in, dec_tar in batches(testenc[:100], batchsize):
    enc = rnnencoder(enc_in, training=False)
    predictions  = rnndecoder([dec_in, enc], training=False)
    preds = tf.argmax(predictions, axis=-1).numpy().flatten()
    targets = dec_tar.numpy().flatten()
    mask = targets != 0
    accuracy_metric.add_batch(predictions=preds[mask], references=targets[mask])

test_acc = accuracy_metric.compute()["accuracy"] * 100
print(f"\nTest Acc: {test_acc:.2f}%")

print(len(pairs))
print(len(valpairs))
print(len(testpairs))

"""LSTM"""

batchsize = 100
d_model = 128
EPOCHS = 25
loss_fn = keras.losses.SparseCategoricalCrossentropy(from_logits=True, ignore_class = 0)
optimizer = keras.optimizers.Adam(learning_rate=0.001)

#encoder

enc_inputs = keras.Input(shape=(None,))
enc_emb  = keras.layers.Embedding(tokenizer.vocab_size, d_model, mask_zero=False)(enc_inputs)
#enc_out, h, c = keras.layers.LSTM(d_model, return_state=True)(enc_emb)
enc_out, fh, bh, fc, bc = keras.layers.Bidirectional(keras.layers.LSTM(d_model, return_state=True, return_sequences = True))(enc_emb)
  #BIDIRECTIONAL IMPLEMENTATION
  #returnsequences = True for obtaining all hidden states for attention

h = keras.layers.Concatenate()([fh, bh])
c = keras.layers.Concatenate()([fc, bc])
encoder = keras.Model(enc_inputs, [enc_out, h, c])

#decoder

dec_inputs = keras.Input(shape=(None,))
enc_out_in = keras.Input(shape=(None, d_model*2))
dec_emb = keras.layers.Embedding(tokenizer.vocab_size, d_model*2, mask_zero=False)(dec_inputs)
h_in = keras.Input(shape=(d_model*2,))
c_in = keras.Input(shape=(d_model*2,))
dec_out, _, _ = keras.layers.LSTM(d_model*2, return_sequences=True, return_state=True)(dec_emb, initial_state=[h_in, c_in])
dec_out = keras.layers.Dropout(0.4)(dec_out)

attention  = keras.layers.AdditiveAttention()([dec_out, enc_out_in])
combined   = keras.layers.Concatenate()([dec_out, attention])
dec_out    = keras.layers.Dense(tokenizer.vocab_size)(combined)

decoder = keras.Model([dec_inputs, enc_out_in, h_in, c_in], dec_out)

import evaluate

losstrack = []
acctrack = []

for epoch in range(1, EPOCHS + 1):

    accuracy_metric = evaluate.load("accuracy")
    #training

    train_loss, steps = 0, 0
    for enc_in, dec_in, dec_tar in batches(encoded[:1500], batchsize):
        with tf.GradientTape() as tape:
            enc_out, h, c  = encoder(enc_in, training=True)
            predictions = decoder([dec_in, enc_out, h, c], training=True)
            loss = loss_fn(dec_tar, predictions)

        grads = tape.gradient(loss, encoder.trainable_variables + decoder.trainable_variables)
        optimizer.apply_gradients(zip(grads, encoder.trainable_variables + decoder.trainable_variables))
        train_loss += loss.numpy()
        steps += 1

    losstrack.append(train_loss/steps)

    #validation

    for enc_in, dec_in, dec_tar in batches(valenc[:500], batchsize):
        enc_out, h, c = encoder(enc_in, training=False)
        predictions = decoder([dec_in, enc_out, h, c], training=False)
        preds = tf.argmax(predictions, axis=-1).numpy().flatten()
        targets = dec_tar.numpy().flatten()
        mask  = targets != 0
        accuracy_metric.add_batch(predictions=preds[mask], references=targets[mask])

    val_acc = accuracy_metric.compute()["accuracy"] * 100
    acctrack.append(val_acc)

    print(f"Epoch {epoch:02d}/{EPOCHS}  Loss: {train_loss/steps:.4f}  Val Acc: {val_acc:.2f}%")

import matplotlib.pyplot as plt
plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(losstrack, label='Train Loss')
plt.title('Loss over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(acctrack, label='Validation Accuracy')
plt.title('Accuracy over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.tight_layout()
plt.show()

#testing

for enc_in, dec_in, dec_tar in batches(testenc[:500], batchsize):
    enc_out, h, c = encoder(enc_in, training=False)
    predictions  = decoder([dec_in, enc_out, h, c], training=False)
    preds = tf.argmax(predictions, axis=-1).numpy().flatten()
    targets = dec_tar.numpy().flatten()
    mask = targets != 0
    accuracy_metric.add_batch(predictions=preds[mask], references=targets[mask])

test_acc = accuracy_metric.compute()["accuracy"] * 100
print(f"\nTest Acc: {test_acc:.2f}%")
